version: "3"
services:
  app:
    hostname: sop.hub
    build: ./app
    ports:
      - 80:80
    environment:
      FLAG: ${FLAG:-fake_flag}
    networks:
      sop_internal:
        ipv4_address: 172.16.0.10

  bot:
    build: ./bot
    ports:
      - 8000:8000
    privileged: true
    networks:
      sop_internal:
        ipv4_address: 172.16.0.11

networks:
  sop_internal:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
